import Classic.Cesar;
import Crackers.FrequencyAnalyzer;

public class Main {
    public static void main(String[] args) {
        Cesar cesar = new Cesar(1);   
        FrequencyAnalyzer fa = new FrequencyAnalyzer();


        // Winner Alphabeth
        char[] frequencyAlphabeth = {'a', 'e','s', 'o', 'i', 'n', 'r', 'l', 'c', 't', 'd', 'm', 'u', 'p', 'y', 'v','h', 'f', 'b', 'g', 'w', 'k', 'x', 'j', 'q', 'z'};

        String text = "CKFIOPGJIK LMPGLKOCKO OGRIMLKLMO FKOPKNQMOP JGOLIKOMOC KFIOPGJIKL MCKOCQRFKO LMRCKOMOFG HAJMOCIAJM OWMORCKTGO SKPJIRIGOW SCMAMWGOOM NGJMOWOIMJ TGOHKMOPJG OWGXIRIKCM OMNQNKSKCK AJKGSJMOGJ MOWGSJIHIL GOOMMNXJMN PKJGNOIMHS JMHKNPQTIM JGNQNKCQRF KRGNOPKNPM TMCKLKQNKO TMRMOWGPJK OXJKNRKWKA IMJPKCQRFK BQMPMJHING OIMHSJMRGN CKPJKNOXGJ HKRIGNJMTG CQRIGNKJIK LMPGLKCKOG RIMLKLGMCF QNLIHIMNPG LMCKORCKOM OMNSQYNKMN CKOKNPMJIG JMOMSGRKOF IOPGJIRKOM NRGNPJKHGO RKOISGJPGL KOSKJPMOQN KRGHSCMPKL IXMJMNRIKR IGNLMCKOGR IMLKLMNLIT MJOGOMOPKH MNPGOQNKHQ CPISCMMORK CKYJKLQKCL MRGNLIRIGN MOOGRIKCMO MNCKKNPIYQ KJGHKFKCCK HGOSKPJIRI GOSCMAMWGO WMORCKTGOM NCKMLKLHML IKOMNGJMOX MQLKCMOTKO KCCGOHKMOP JGOGXIRIKC MOWOIMJTGO WKLMHKOMNR KOIPGLKOMO PKORCKOMOP GLKTIKMNRG NPJKHGOYJK LKRIGNMOMO SMRIKCMO";

        System.out.println(fa.replaceText(text, frequencyAlphabeth));
    }
}
